Update dependencies to fix build
master is currently broken because platforms crate yanked the old versions.

```
cargo install -f --path .
  Installing cargo-asm v0.1.17 (/Users/taiki/projects/cargo-asm)
    Updating crates.io index
error: failed to compile `cargo-asm v0.1.17 (/Users/taiki/projects/cargo-asm)`, intermediate artifacts can be found at `/Users/taiki/projects/cargo-asm/target`

Caused by:
  failed to select a version for the requirement `platforms = "^0.2"`
  candidate versions found which didn't match: 2.0.0, 1.1.0, 1.0.3, ...
  location searched: crates.io index
  required by package `cargo-asm v0.1.17 (/Users/taiki/projects/cargo-asm)
```